/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import Controlador.Controlador;
import Modelo.Carton;
import Modelo.GestorMemoria;
import java.awt.Color;
import java.awt.Component;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JOptionPane;


/**
 *
 * @author Braya
 */
public class VentanaCartones extends javax.swing.JInternalFrame{

    private Controlador controlador;
    private boolean suppressOnClose = false;

    
    /**
     * Creates new form VentanaCartones
     */
    public VentanaCartones() {
        initComponents();
        // Rellenar combos con opciones
        cmbModo.removeAllItems();
        for (Modelo.EnumModoJuego m : Modelo.EnumModoJuego.values()) {
            cmbModo.addItem(m.name());
        }
        cmbTipoJuego.removeAllItems();
        for (Modelo.EnumTipoJuego t : Modelo.EnumTipoJuego.values()) {
            cmbTipoJuego.addItem(t.name());
        }

        // Cuando se cierre esta ventana, eliminar el cartón asociado (si existe)
        this.addInternalFrameListener(new javax.swing.event.InternalFrameAdapter() {
            @Override
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent e) {
                String id = tblId.getText();
                if (suppressOnClose) {
                    return; // Evitar acción si se cierra programáticamente desde el controlador
                }
                if (controlador != null && id != null && !id.isEmpty()) {
                    controlador.eliminarCarton(id);
                }
            }
        });
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        PCrearCartones = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tblId = new javax.swing.JTextField();
        cmbModo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        btnCrearCarton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        cmbTipoJuego = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btnGuaradarManual = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();

        jPasswordField1.setText("jPasswordField1");

        setClosable(true);
        setResizable(true);
        setTitle("Administrar Cartones");

        PCrearCartones.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 0));
        jLabel2.setText("Cartones");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 204, 204));
        jLabel3.setText("Id del carton");

        cmbModo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbModoActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setText("Modo Juego");

        btnCrearCarton.setBackground(new java.awt.Color(255, 204, 0));
        btnCrearCarton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCrearCarton.setText("Crear Cartones");
        btnCrearCarton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearCartonActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 255));
        jLabel6.setText("Tipo Juego");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Iconos/ModJuego.png"))); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Iconos/TipoJuego-removebg-preview.png"))); // NOI18N

        javax.swing.GroupLayout PCrearCartonesLayout = new javax.swing.GroupLayout(PCrearCartones);
        PCrearCartones.setLayout(PCrearCartonesLayout);
        PCrearCartonesLayout.setHorizontalGroup(
            PCrearCartonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PCrearCartonesLayout.createSequentialGroup()
                .addGroup(PCrearCartonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PCrearCartonesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PCrearCartonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PCrearCartonesLayout.createSequentialGroup()
                                .addComponent(cmbModo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PCrearCartonesLayout.createSequentialGroup()
                                .addGroup(PCrearCartonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbTipoJuego, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnCrearCarton))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(PCrearCartonesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PCrearCartonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tblId, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(PCrearCartonesLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel2)
                        .addGap(54, 54, 54)
                        .addComponent(jLabel1)))
                .addGap(0, 6, Short.MAX_VALUE))
        );
        PCrearCartonesLayout.setVerticalGroup(
            PCrearCartonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PCrearCartonesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(8, 8, 8)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tblId, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PCrearCartonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbModo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PCrearCartonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PCrearCartonesLayout.createSequentialGroup()
                        .addComponent(cmbTipoJuego, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCrearCarton))
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 0, 0));
        jLabel5.setText("Tabla Carton");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, -1));

        btnGuaradarManual.setBackground(new java.awt.Color(0, 204, 204));
        btnGuaradarManual.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnGuaradarManual.setText("Guardar Numero");
        btnGuaradarManual.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnGuaradarManual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuaradarManualActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuaradarManual, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, 20));

        btnEliminar.setBackground(new java.awt.Color(0, 204, 204));
        btnEliminar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEliminar.setText("Eliminar Carton");
        btnEliminar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, -1, -1));

        jLabel37.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel37.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 60, 30));

        jLabel38.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(204, 102, 0));
        jLabel38.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel38.setText("B");
        jLabel38.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 60, 30));

        jLabel39.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel39.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 60, 30));

        jLabel40.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel40.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 60, 30));

        jLabel41.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel41.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 60, 30));

        jLabel42.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel42.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 330, 60, 30));

        jLabel43.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(153, 0, 153));
        jLabel43.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel43.setText("I");
        jLabel43.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 60, 30));

        jLabel44.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(0, 51, 153));
        jLabel44.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel44.setText("N");
        jLabel44.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 60, 30));

        jLabel45.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(0, 102, 102));
        jLabel45.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel45.setText("G");
        jLabel45.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 60, 30));

        jLabel46.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(0, 204, 0));
        jLabel46.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel46.setText("O");
        jLabel46.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, 60, 30));

        jLabel48.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel48.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 60, 30));

        jLabel49.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel49.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 60, 30));

        jLabel50.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel50.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 60, 30));

        jLabel51.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel51.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 60, 30));

        jLabel52.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel52.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 60, 30));

        jLabel53.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel53.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 60, 30));

        jLabel54.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel54.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, 60, 30));

        jLabel55.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel55.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, 60, 30));

        jLabel60.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel60.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, 60, 30));

        jLabel61.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel61.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 280, 60, 30));

        jLabel62.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel62.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 60, 30));

        jLabel63.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel63.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 60, 30));

        jLabel64.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel64.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 60, 30));

        jLabel65.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel65.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 60, 30));

        jLabel66.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel66.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 60, 30));

        jLabel67.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel67.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 60, 30));

        jLabel68.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel68.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 60, 30));

        jLabel69.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel69.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, 60, 30));

        jLabel70.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel70.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, 60, 30));

        jLabel71.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel71.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, 60, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PCrearCartones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(PCrearCartones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        String id = tblId.getText();
        if (controlador != null) {
            controlador.eliminarCarton(id);
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void cmbModoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbModoActionPerformed

    }//GEN-LAST:event_cmbModoActionPerformed

    private void btnCrearCartonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearCartonActionPerformed
        String id = tblId.getText();
        String modoSel = (String) cmbModo.getSelectedItem();
        String tipoSel = (String) cmbTipoJuego.getSelectedItem();
        Modelo.EnumModoJuego modo = Modelo.EnumModoJuego.valueOf(modoSel);
        Modelo.EnumTipoJuego tipo = Modelo.EnumTipoJuego.valueOf(tipoSel);
        if (controlador != null) {
            controlador.crearCarton(id, modo, tipo);
        }
    }//GEN-LAST:event_btnCrearCartonActionPerformed

    private void btnGuaradarManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuaradarManualActionPerformed
        // Pedir fila, columna y valor para edición manual
        String id = tblId.getText();
        if (id == null || id.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese el ID del cartón antes de editar.");
            return;
        }

        String filas = JOptionPane.showInputDialog(this, "Fila (1-5):");
        if (filas == null) return;
        String colum = JOptionPane.showInputDialog(this, "Columna (1-5):");
        if (colum == null) return;
        String valor = JOptionPane.showInputDialog(this, "Valor (0 para borrar):");
        if (valor == null) return;

        try {
            int fila = Integer.parseInt(filas) - 1;
            int col = Integer.parseInt(colum) - 1;
            int val = Integer.parseInt(valor);
            if (controlador != null) {
                controlador.solicitarIngresoManual(id, fila, col, val);
                // Actualizar vista local
                // Intentar obtener el cartón desde el gestor y mostrarlo
                Carton c = GestorMemoria.obtenerInstancia().obtenerCarton(id);
                if (c != null) mostrarCarton(c);
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Entrada inválida.");
        }
    }//GEN-LAST:event_btnGuaradarManualActionPerformed

    

    public void setControlador(Controlador controlador) {
        this.controlador = controlador;
    }

    public void setSuppressOnClose(boolean suppress) {
        this.suppressOnClose = suppress;
    }

    public void mostrarCarton(Modelo.Carton carton) {
        // Muestra el cartón en un diálogo sencillo (implementación mínima)
        int[][] nums = carton.getNumerosCarton();
        // Asegurar que el campo ID muestre el ID del cartón actual
        tblId.setText(carton.getId());
        StringBuilder sb = new StringBuilder();
        sb.append("Cartón ID: ").append(carton.getId()).append("\n");
        for (int i = 0; i < 5; i++) {
            for (int j = 0; j < 5; j++) {
                sb.append(String.format("%3d", nums[i][j]));
            }
            sb.append("\n");
        }
        JOptionPane.showMessageDialog(this, sb.toString(), "Cartón", javax.swing.JOptionPane.INFORMATION_MESSAGE);

        // También actualizar la grilla visual del panel 
        List<JLabel> labels = new ArrayList<>();
        for (Component c : jPanel1.getComponents()) {
            if (c instanceof JLabel) {
                JLabel l = (JLabel) c;
                // Ignorar encabezados B I N G O (fuente más grande)
                if (l.getFont().getSize() <= 14) {
                    labels.add(l);
                }
            }
        }

        // Ordenar por posición (y, x)
        labels.sort((a, b) -> {
            int dy = a.getY() - b.getY();
            if (dy != 0) return dy;
            return a.getX() - b.getX();
        });

        // Asegurar que haya al menos 25 labels detectados
        int label = 25;
        if (labels.size() >= label) {
            int idx = 0;
            for (int i = 0; i < 5; i++) {
                for (int j = 0; j < 5; j++) {
                    JLabel lab = labels.get(idx++);
                    int val = nums[i][j];
                    lab.setText(val == 0 ? "" : String.valueOf(val));
                    lab.setOpaque(false);
                    lab.setBackground(null);
                    lab.setForeground(java.awt.Color.BLACK);
                }
            }
        }
    }

    public void insertarNumeroCarton(Modelo.Carton carton) {
        mostrarCarton(carton);
    }

    public void marcarNumeroEnCarton(int numero) {
        for (Component c : jPanel1.getComponents()) {
            if (c instanceof JLabel) {
                JLabel l = (JLabel) c;
                String text = l.getText();
                if (text != null && !text.isEmpty()) {
                    try {
                        int val = Integer.parseInt(text);
                        if (val == numero) {
                            l.setOpaque(true);
                            l.setBackground(java.awt.Color.GREEN);
                            l.setForeground(java.awt.Color.BLACK);
                        }
                    } catch (NumberFormatException ex) {
                        // ignorar
                    }
                }
            }
        }
    }

    public void reiniciarVisual() {
        for (Component c : jPanel1.getComponents()) {
            if (c instanceof JLabel) {
                javax.swing.JLabel l = (JLabel) c;
                l.setOpaque(false);
                l.setBackground(null);
                l.setForeground(Color.BLACK);
            }
        }
    }

    public void limpiarDatosCarton() {
        // Limpiar campo de ID
        tblId.setText("");

        // Limpiar textos y estilos de las etiquetas del cartón
        for (Component c : jPanel1.getComponents()) {
            if (c instanceof JLabel) {
                JLabel l = (JLabel) c;
                String txt = l.getText();
                // No borrar los encabezados "B","I","N","G","O" ni el título "Tabla Carton"
                if (txt != null) {
                    String t = txt.trim();
                    if (t.equals("B") || t.equals("I") || t.equals("N") || t.equals("G") || t.equals("O") || t.equals("Tabla Carton")) {
                        continue;
                    }
                }
                l.setText("");
                l.setOpaque(false);
                l.setBackground(null);
                l.setForeground(Color.BLACK);
            }
        }
    }

    public String getIdTexto() {
        return tblId.getText();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PCrearCartones;
    private javax.swing.JButton btnCrearCarton;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuaradarManual;
    private javax.swing.JComboBox<String> cmbModo;
    private javax.swing.JComboBox<String> cmbTipoJuego;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField tblId;
    // End of variables declaration//GEN-END:variables

}

