/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import Controlador.Controlador;
import Modelo.EnumModoJuego;
import Modelo.EnumTipoJuego;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import java.awt.event.ActionListener;

/**
 *
 * @author Braya
 */
public class VentanaTombola extends javax.swing.JInternalFrame {

    private Controlador controlador;

    /**
     * Creates new form VentanaTombola
     */
    public VentanaTombola() {
        initComponents();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblultimoNumero = new javax.swing.JLabel();
        btnReiniciar = new javax.swing.JButton();
        btnGenerarNumero1 = new javax.swing.JButton();

        jLabel3.setText("jLabel3");

        jButton1.setText("jButton1");

        setClosable(true);
        setTitle("Tombola");

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Tombola");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Ultimo Numero");

        lblultimoNumero.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblultimoNumero.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnReiniciar.setBackground(new java.awt.Color(255, 204, 51));
        btnReiniciar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnReiniciar.setText("Reiniciar");
        btnReiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReiniciarActionPerformed(evt);
            }
        });

        btnDesmarcar = new javax.swing.JButton();
        btnDesmarcar.setBackground(new java.awt.Color(255, 204, 51));
        btnDesmarcar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDesmarcar.setText("Desmarcar Último");
        btnDesmarcar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                if (controlador != null) controlador.desmarcarNumero();
            }
        });

        btnGenerarNumero1.setBackground(new java.awt.Color(255, 204, 51));
        btnGenerarNumero1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGenerarNumero1.setText("Generar Numero");
        btnGenerarNumero1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarNumero1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblultimoNumero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnReiniciar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnDesmarcar)) )
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(129, Short.MAX_VALUE)
                    .addComponent(btnGenerarNumero1)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(25, 25, 25)
                        .addComponent(lblultimoNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnReiniciar)
                        .addComponent(btnDesmarcar)))
                .addContainerGap(8, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(53, 53, 53)
                    .addComponent(btnGenerarNumero1)
                    .addContainerGap(56, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReiniciarActionPerformed
        if (controlador != null) {
            controlador.reiniciarJuego();
        } else {
            JOptionPane.showMessageDialog(this, "Controlador no asignado.");
        }
    }//GEN-LAST:event_btnReiniciarActionPerformed

    private void btnGenerarNumero1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarNumero1ActionPerformed
        if (controlador == null) {
            JOptionPane.showMessageDialog(this, "Controlador no asignado.");
            return;
        }

        String[] opciones = {"Automático", "Manual"};
        int sel = JOptionPane.showOptionDialog(this, "Seleccione modo de extracción:", "Extraer Número",
                JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, opciones, opciones[0]);

        if (sel == 0) {
            controlador.generarNumeroAutomatico();
        } else if (sel == 1) {
            String entrada = JOptionPane.showInputDialog(this, "Ingrese número a sacar (1-75):");
            if (entrada != null && !entrada.isEmpty()) {
                try {
                    int numero = Integer.parseInt(entrada);
                    controlador.marcarNumeroJuego(numero);
                } catch (NumberFormatException ex) {
                    JOptionPane.showMessageDialog(this, "Número inválido.");
                }
            }
        }
    }//GEN-LAST:event_btnGenerarNumero1ActionPerformed

    public void setControlador(Controlador controlador) {
        this.controlador = controlador;
    }

    public void mostrarUltimoNumero(int numero) {
        final String text = numero <= 0 ? "" : String.valueOf(numero);
        SwingUtilities.invokeLater(() -> lblultimoNumero.setText(text));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerarNumero1;
    private javax.swing.JButton btnReiniciar;
    private javax.swing.JButton btnDesmarcar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblultimoNumero;
    // End of variables declaration//GEN-END:variables
}
