/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.Controlador;
import Modelo.Carton;
import Modelo.EnumModoJuego;
import Modelo.EnumTipoJuego;
import javax.swing.JOptionPane;


/**
 *
 * @author Braya
 */
public class VentanaPrincipal extends javax.swing.JFrame implements IVista {

    private Controlador controlador;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName());


    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        // Crear controlador vinculando esta vista
        this.controlador = new Controlador(this);
        

        // No crear internal frames por defecto: se instanciarán al abrir el menú.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPanePrincipal = new javax.swing.JDesktopPane() {
            private final java.awt.Image imagenFondo = new javax.swing.ImageIcon(
                getClass().getResource("/Vista/Iconos/bingo-lottery-balls-and-tickets-background-vector.jpg")
            ).getImage();

            @Override
            protected void paintComponent(java.awt.Graphics g) {
                super.paintComponent(g);
                g.drawImage(imagenFondo, 0, 0, getWidth(), getHeight(), this);
            }
        };
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        desktopPanePrincipal.setMaximumSize(null);
        desktopPanePrincipal.setPreferredSize(null);

        javax.swing.GroupLayout desktopPanePrincipalLayout = new javax.swing.GroupLayout(desktopPanePrincipal);
        desktopPanePrincipal.setLayout(desktopPanePrincipalLayout);
        desktopPanePrincipalLayout.setHorizontalGroup(
            desktopPanePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 624, Short.MAX_VALUE)
        );
        desktopPanePrincipalLayout.setVerticalGroup(
            desktopPanePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 362, Short.MAX_VALUE)
        );

        getContentPane().add(desktopPanePrincipal, java.awt.BorderLayout.CENTER);

        jMenu1.setText("Cartones");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N

        jMenuItem1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jMenuItem1.setText("Cartones");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Tombola");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N

        jMenuItem2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jMenuItem2.setText("Tombola");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Tablero");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N

        jMenuItem3.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jMenuItem3.setText("Tablero");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuBar1.add(jMenu3);
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // Abrir ventana de cartones
        for (java.awt.Component c : desktopPanePrincipal.getComponents()) {
            if (c instanceof VentanaCartones) {
                ((VentanaCartones) c).setVisible(true);
                ((VentanaCartones) c).toFront();
                return;
            }
        }
        VentanaCartones v = new VentanaCartones();
        v.setControlador(this.controlador);
        desktopPanePrincipal.add(v);
        v.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        for (java.awt.Component c : desktopPanePrincipal.getComponents()) {
            if (c instanceof VentanaTombola) {
                ((VentanaTombola) c).setVisible(true);
                ((VentanaTombola) c).toFront();
                return;
            }
        }
        VentanaTombola v = new VentanaTombola();
        v.setControlador(this.controlador);
        desktopPanePrincipal.add(v);
        v.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        for (java.awt.Component c : desktopPanePrincipal.getComponents()) {
            if (c instanceof VentanaTablero) {
                ((VentanaTablero) c).setVisible(true);
                ((VentanaTablero) c).toFront();
                return;
            }
        }
        VentanaTablero v = new VentanaTablero();
        v.setControlador(this.controlador);
        desktopPanePrincipal.add(v);
        v.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    // ==== Implementación mínima de IVista: delega a internal frames o muestra mensajes ====
    @Override
    public void mostrarCarton(Carton carton) {
        // Buscar VentanaCartones y delegar
        for (java.awt.Component c : desktopPanePrincipal.getComponents()) {
            if (c instanceof VentanaCartones) {
                ((VentanaCartones) c).mostrarCarton(carton);
                return;
            }
        }
        JOptionPane.showMessageDialog(this, "Cartón creado: " + carton.getId());
    }

    @Override
    public void actualizarTablero(int numero) {
        for (java.awt.Component c : desktopPanePrincipal.getComponents()) {
            if (c instanceof VentanaTablero) {
                ((VentanaTablero) c).marcarNumero(numero);
                return;
            }
        }
    }

    @Override
    public void insertarNumeroCarton(Carton Carton) {
        // Delegar a VentanaCartones si existe
        for (java.awt.Component c : desktopPanePrincipal.getComponents()) {
            if (c instanceof VentanaCartones) {
                ((VentanaCartones) c).insertarNumeroCarton(Carton);
                return;
            }
        }
    }

    @Override
    public void eliminarCarton(String id) {
        // Intentar limpiar/cerrar todas las VentanaCartones abiertas (más robusto)
        boolean any = false;
        java.util.List<java.awt.Component> toRemove = new java.util.ArrayList<>();
        for (java.awt.Component c : desktopPanePrincipal.getComponents()) {
            if (c instanceof VentanaCartones) {
                VentanaCartones vc = (VentanaCartones) c;
                String idVisible = vc.getIdTexto();
                // Si el ID coincide o el campo está vacío, cerramos/limpiamos para evitar restos visuales
                if (idVisible != null && (idVisible.equals(id) || idVisible.isEmpty())) {
                    vc.setSuppressOnClose(true);
                    vc.limpiarDatosCarton();
                    vc.setVisible(false);
                    toRemove.add(vc);
                    any = true;
                }
            }
        }

        // Remover fuera del bucle para evitar ConcurrentModification
        for (java.awt.Component c : toRemove) {
            desktopPanePrincipal.remove(c);
        }
        if (!toRemove.isEmpty()) {
            desktopPanePrincipal.revalidate();
            desktopPanePrincipal.repaint();
        }

        if (!any) {
            JOptionPane.showMessageDialog(this, "Cartón eliminado: " + id);
        }
    }

    @Override
    public void mostarUltimoNumero(int numero) {
        for (java.awt.Component c : desktopPanePrincipal.getComponents()) {
            if (c instanceof VentanaTombola) {
                ((VentanaTombola) c).mostrarUltimoNumero(numero);
                return;
            }
        }
    }

    @Override
    public void mostarGanador(String id, String tipoVictoria) {
        JOptionPane.showMessageDialog(this, "Ganador: " + id + " (" + tipoVictoria + ")");
    }

    @Override
    public void mostarMensaje(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje);
    }

    @Override
    public void mostrarError(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje, "Error", JOptionPane.ERROR_MESSAGE);
    }

    @Override
    public void actualizarVista() {
        // Propagar último número marcado a los cartones para que se pinten
        Integer ultimo = Modelo.GestorMemoria.obtenerInstancia().obtenerTombola().getUltimoNumero();
        if (ultimo != null && ultimo > 0) {
            for (java.awt.Component c : desktopPanePrincipal.getComponents()) {
                if (c instanceof VentanaCartones) {
                    ((VentanaCartones) c).marcarNumeroEnCarton(ultimo);
                }
            }
        }
    }

    @Override
    public void reiniciarVista() {
        for (java.awt.Component c : desktopPanePrincipal.getComponents()) {
            if (c instanceof VentanaTablero) {
                ((VentanaTablero) c).reiniciarTablero();
            }
            if (c instanceof VentanaTombola) {
                ((VentanaTombola) c).mostrarUltimoNumero(0);
            }
            if (c instanceof VentanaCartones) {
                ((VentanaCartones) c).reiniciarVisual();
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPanePrincipal;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    // End of variables declaration//GEN-END:variables

 
}
